### ISSUE TITLE
Document describes relationship validation is too strict 

### ISSUE THREAD

**Issue by agustin-mrtz** [spdx/spdx-java-model-2_X#3]
Per the [specification](https://spdx.github.io/spdx-spec/v2.3/relationships-between-SPDX-elements/) 
```
Relationship 	Description 	                                                Example
DESCRIBES 	Is to be used when SPDXRef-DOCUMENT describes SPDXRef-A. 	An SPDX document WildFly.spdx describes package ‘WildFly’. Note this is a logical relationship to help organize related items within an SPDX document that is mandatory if more than one package or set of files (not in a package) is present.
```

Specifically 
```
 Note this is a logical relationship to help organize related items within an SPDX document that is mandatory if more than one package or set of files (not in a package) is present.
```

According to the specification, this [check](https://github.com/spdx/spdx-java-model-2_X/blob/main/src/main/java/org/spdx/library/model/v2/SpdxDocument.java#L324) is incorrect and thus declares documents with a single package as missing a `DESCRIBES` relationship and therefore falsely considered invalid.

**Comment by goneall** [comment]
Thanks @agustin-mrtz for reporting this.  I agree this check isn't valid according to the spec.  We could just remove the check, or, add some extra logic to only report an error if there is more than one package and no document describes.

**Comment by agustin-mrtz** [comment]
>add some extra logic to only report an error if there is more than one package and no document describes. 

I would be in favor of this option.
