### ISSUE TITLE
Documents can be created with multiple packages having "DESCRIBES" relationships

### ISSUE THREAD

**Issue by agustin-mrtz** [spdx/spdx-java-model-2_X#4]
As currently implemented, SPDX SBOMs with multiple packages containing `DESCRIBES` relationships are considered valid. The specification does not make it clear if an SPDX document can describe more than one package.

**Comment by goneall** [comment]
I believe the intent of the spec is to allow this scenario, although the spec may not be clear on the subject.

I recall discussions in the spec where use cases were presented for having multiple documents being "described".

**Comment by agustin-mrtz** [comment]
Sounds good, thank you for the clarification.
